# Builds WindowsInstaller.exe - one portable exe, no dependencies, no SDK needed.
# Uses only the C# compiler that ships with Windows (.NET Framework 4.x, C# 5).
#
#   .\build.ps1                    -> dev build: version from the latest git tag + "-dev"
#   .\build.ps1 -Version 1.2.0     -> release build (used by .github/workflows/release.yml)
#   .\build.ps1 -Test              -> also runs the exe's self-test after building
param(
    [string]$Version = "",
    [string]$Repo = "barnibeats/Windows-installer",   # where the app looks for updates
    [switch]$Test
)
$ErrorActionPreference = "Stop"
$root = $PSScriptRoot
$src  = Join-Path $root "src"
$obj  = Join-Path $root "obj"
New-Item -ItemType Directory -Force $obj | Out-Null

# --- icon: four gradient tiles, same as the logo in the app ---------------------------------------
Add-Type -AssemblyName System.Drawing
function New-TilePng([int]$size) {
    $bmp = New-Object System.Drawing.Bitmap $size, $size
    $g = [System.Drawing.Graphics]::FromImage($bmp)
    $g.SmoothingMode = "AntiAlias"; $g.Clear([System.Drawing.Color]::Transparent)
    $pairs = @(@("#7c5cff","#00d4ff"), @("#00d4ff","#3ddc97"), @("#ff4fd8","#7c5cff"), @("#ffb84f","#ff4fd8"))
    $gap = [math]::Max(1, [int]($size * 0.08)); $pad = [int]($size * 0.06)
    $t = [int](($size - 2 * $pad - $gap) / 2); $r = [math]::Max(1, [int]($t * 0.22))
    for ($i = 0; $i -lt 4; $i++) {
        $x = $pad + ($i % 2) * ($t + $gap); $y = $pad + [math]::Floor($i / 2) * ($t + $gap)
        $rect = New-Object System.Drawing.Rectangle $x, $y, $t, $t
        $br = New-Object System.Drawing.Drawing2D.LinearGradientBrush $rect, ([System.Drawing.ColorTranslator]::FromHtml($pairs[$i][0])), ([System.Drawing.ColorTranslator]::FromHtml($pairs[$i][1])), 45
        $p = New-Object System.Drawing.Drawing2D.GraphicsPath
        $d = 2 * $r
        $p.AddArc($x, $y, $d, $d, 180, 90); $p.AddArc($x + $t - $d, $y, $d, $d, 270, 90)
        $p.AddArc($x + $t - $d, $y + $t - $d, $d, $d, 0, 90); $p.AddArc($x, $y + $t - $d, $d, $d, 90, 90)
        $p.CloseFigure(); $g.FillPath($br, $p)
    }
    $g.Dispose()
    $ms = New-Object System.IO.MemoryStream
    $bmp.Save($ms, [System.Drawing.Imaging.ImageFormat]::Png); $bmp.Dispose()
    return ,$ms.ToArray()
}
$sizes = 16, 24, 32, 48, 64, 128, 256
$pngs = $sizes | ForEach-Object { ,(New-TilePng $_) }
$ico = New-Object System.IO.MemoryStream
$w = New-Object System.IO.BinaryWriter $ico
$w.Write([UInt16]0); $w.Write([UInt16]1); $w.Write([UInt16]$sizes.Count)
$offset = 6 + 16 * $sizes.Count
for ($i = 0; $i -lt $sizes.Count; $i++) {
    $s = $sizes[$i]; $b = if ($s -ge 256) { 0 } else { $s }
    $w.Write([byte]$b); $w.Write([byte]$b); $w.Write([byte]0); $w.Write([byte]0)
    $w.Write([UInt16]1); $w.Write([UInt16]32); $w.Write([UInt32]$pngs[$i].Length); $w.Write([UInt32]$offset)
    $offset += $pngs[$i].Length
}
foreach ($p in $pngs) { $w.Write($p) }
$w.Flush(); [System.IO.File]::WriteAllBytes("$obj\app.ico", $ico.ToArray())

# --- version ---------------------------------------------------------------------------------------
if (-not $Version) {
    $tag = ""
    try { $tag = (git -C $root describe --tags --abbrev=0 2>$null) } catch { }
    if (-not $tag) { $tag = "0.0.0" }
    $Version = ($tag -replace '^v', '') + "-dev"
}
$Version = $Version -replace '^v', ''
$numeric = ([regex]::Match($Version, '^\d+(\.\d+){0,3}')).Value
if (-not $numeric) { $numeric = "0.0.0" }
@"
// Generated by build.ps1 - do not edit.
[assembly: System.Reflection.AssemblyTitle("Windows Installer")]
[assembly: System.Reflection.AssemblyProduct("Windows Installer")]
[assembly: System.Reflection.AssemblyVersion("$numeric")]
[assembly: System.Reflection.AssemblyFileVersion("$numeric")]
[assembly: System.Reflection.AssemblyInformationalVersion("$Version")]
static class AppInfo
{
    public const string Version = "$Version";
    public const string Repo = "$Repo";
}
"@ | Set-Content -Encoding UTF8 "$obj\AppInfo.cs"

# --- compile ---------------------------------------------------------------------------------------
$fx  = "$env:WINDIR\Microsoft.NET\Framework64\v4.0.30319"
if (-not (Test-Path "$fx\csc.exe")) { $fx = "$env:WINDIR\Microsoft.NET\Framework\v4.0.30319" }
$out = Join-Path $root "WindowsInstaller.exe"
$files = Get-ChildItem $src -Filter *.cs | Where-Object { $_.Name -ne "AppInfo.cs" } | ForEach-Object { $_.FullName }
& "$fx\csc.exe" /nologo /target:winexe /platform:anycpu /optimize+ /codepage:65001 /out:"$out" `
    /win32icon:"$obj\app.ico" /win32manifest:"$src\app.manifest" `
    /r:System.Windows.Forms.dll /r:System.Drawing.dll /r:System.Core.dll /r:System.Management.dll /r:System.Web.Extensions.dll `
    $files "$obj\AppInfo.cs"
if ($LASTEXITCODE -ne 0) { throw "Build failed" }
Write-Host ("Built: {0} v{1} ({2:N0} KB)" -f $out, $Version, ((Get-Item $out).Length / 1KB))

if ($Test) {
    $report = Join-Path $obj "selftest.txt"
    $p = Start-Process -FilePath $out -ArgumentList "--selftest", "`"$report`"" -Wait -PassThru
    if (Test-Path $report) { Get-Content $report -Encoding UTF8 }
    if ($p.ExitCode -ne 0) { throw "Self-test failed" }
}
