// Generated by build.ps1 - this copy is only for editors; the build overwrites it.
static class AppInfo
{
    public const string Version = "0.0.0-dev";
    public const string Repo = "barnibeats/Windows-installer";
}
